fetch-blockly:
	wget https://github.com/google/blockly/releases/download/blockly-v12.3.1/blockly-12.3.1.tgz
	tar xf blockly-12.3.1.tgz && mv package blockly-12.3.1

fetch-shadow-block-converter:
	wget https://cdn.jsdelivr.net/npm/@blockly/shadow-block-converter@7.0.4/dist/index.js
	mv index.js shadow-block-converter-7.0.4/dist/index.js

fetch-toolbox-search:
	wget https://cdn.jsdelivr.net/npm/@blockly/toolbox-search@3.1.2/dist/index.js
	mv index.js toolbox-search-3.1.2/dist/index.js
