_then_2(
  _then_2(
    _primitiveLoadPackageSequence_1([
      "Piecewise",
      "Prototype",
      "ArrayBuffer",
      "AssociationList",
      "Bag",
      "ByteArray",
      "CategoryDictionary",
      "Float32Array",
      "Float64Array",
      "Heap",
      "LinkedList",
      "PriorityQueue",
      "RunArray",
      "Set",
      "Slice",
      "Stack",
      "SortedList",
      "Tree",
      "Tuple",
      "WeakMap",
      "BitSet",
      "Graph",
      "ResidueSet",
      "Complex",
      "Fraction",
      "Interval",
      "LargeInteger",
      "Residue",
      "Decimal",
      "Angle",
      "CartesianCoordinates",
      "Circle",
      "Length",
      "Plane",
      "PolarCoordinates",
      "PlanarCoordinates",
      "Matrix22",
      "Matrix33",
      "Projection3",
      "Rectangle",
      "FourVector",
      "CylindricalCoordinates",
      "Sphere",
      "SphericalCoordinates",
      "Point",
      "Colour",
      "Plot",
      "HelpIndex",
      "Bessel",
      "Binomial",
      "Elementwise",
      "Fourier",
      "Gamma",
      "Matrix",
      "Permutations",
      "Primes",
      "WindowFunction",
      "Iterator",
      "Stream",
      "PositionableStream",
      "WriteStream",
      "BlockStream",
      "CollectionStream",
      "MutableCollectionStream",
      "AsciiStream",
      "Utf8Stream",
      "AliasMethod",
      "LinearCongruential",
      "MersenneTwister",
      "ProbabilityDistribution",
      "Sfc32",
      "SplitMix",
      "Blob",
      "Event",
      "EventTarget",
      "File",
      "FilePath",
      "FileSystem",
      "Headers",
      "LibraryItem",
      "Method",
      "MessageEvent",
      "Navigator",
      "Scheduling",
      "Storage",
      "SubProcess",
      "Trait",
      "Transcript",
      "Type",
      "Url",
      "UrlQueryParameters",
      "WebSocket",
      "Window",
      "Location",
      "Reflection",
      "AsciiString",
      "Markdown",
      "QuotedString",
      "RegExp",
      "Unicode",
      "Clock",
      "Date",
      "Duration",
      "Frequency",
      "TimeStamp",
      "Mass",
      "SiUnit",
      "Categories",
      "DocumentTest",
      "HelpFile",
      "TerseGuide",
      "TerseReference",
      "SoundFile",
      "Apl",
    ]),
    function (_unused) {
      /* ArityCheck */
      if (arguments.length !== 1) {
        const errorMessage =
          "Arity: expected 1, _unused"; /* console.error(errorMessage); */
        throw new Error(errorMessage);
      }
      /* Statements */
      return _primitiveReadLocalBinaryFile_1("config/preferences.json");
    },
  ),
  function (_byteArray) {
    /* ArityCheck */
    if (arguments.length !== 1) {
      const errorMessage =
        "Arity: expected 1, _byteArray"; /* console.error(errorMessage); */
      throw new Error(errorMessage);
    }
    /* Statements */
    return _atPut_3(
      _cache_1(_system),
      "preferences",
      _parseJson_1(_utf8String_1(_byteArray)),
    );
  },
);
